### ISSUE TITLE
Add a website

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Open-Source-Internships#101]
I just need a HTML type website, hosted on Heroku.

- Sign up in an [Heroku](https://id.heroku.com/login) account.
- Deploy the website.
- Take credentials from me.
- Deploy on my Heroku account.

**Comment by mridubhatnagar** [comment]
- Have signed up on the Heroku account
Once I create the website and deploy. I'll take credentials from you.

**Comment by tapaswenipathak** [comment]
@mridubhatnagar great work, can you add the deployment files as well?
