### ISSUE TITLE
GitHub API implementation

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Open-Source-Internships#115]
- Take GitHub credentials.
- Fetch the information from readme file and parse as a `json`.
- Deploy this as a Heroku app.
- Take credentials from me.
- Deploy from my heroku account.

Programming language - Python.

cc @shubhank-saxena.

**Comment by shubhank-saxena** [comment]
Okay. I am on it!

**Comment by shubhank-saxena** [comment]
Could you please elaborate more on the requirements? As far as I understand, a user is supposed to take a username, list all the repos, and then parse the required repo's Readme as JSON

**Comment by shubhank-saxena** [comment]
There is no official support of content parsing in the API documentation. What is the alternate way that I can do it?

**Comment by tapaswenipathak** [comment]
You can parse the website, I will be making sure every internship
information added in readme is added in index.html file. I am using my
phone, url you can find in the repository description.

**Comment by tapaswenipathak** [comment]
Closing, extra thoughts. https://github.com/tapaswenipathak/Open-Source-Internships/issues/119 will do.

**Comment by tapaswenipathak** [comment]
Closing, extra thoughts, Django app would do.

**Comment by shubhank-saxena** [comment]
I have achieved all the functionalities as expected. I have parsed the README.md using BeautifulSoup. Was just working on the UI part. So is this issue now closed? Do I have to shift on issue #119?
