### ISSUE TITLE
Django web app

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Open-Source-Internships#119]
Create a Django web application and enable adding an internship from UI.

**Comment by himansingh241** [comment]
Only the admin is allowed to add internships right?

**Comment by mridubhatnagar** [comment]
What all things should the Django web app contain?

**Comment by tapaswenipathak** [comment]
You can look at the OSHC website. People can add internships from the website and only admin will publish.

**Comment by mridubhatnagar** [comment]
Working on this one.
