### ISSUE TITLE
Outreachy Eligibility 

### ISSUE THREAD

**Issue by GLaDO8** [tapaswenipathak/Open-Source-Internships#70]
Outreachy's eligibility criteria are the following

You should be eligible in either of these categories

1) You live anywhere in the world and you identify as a woman (cis or trans), trans man, or genderqueer person (including genderfluid or genderfree).

2) You live in the United States or you are a U.S. national or permanent resident living aboard, AND you are a person of any gender who is Black/African American, Hispanic/Latin@, Native American/American Indian, Alaska Native, Native Hawaiian, or Pacific Islander.

**Comment by palash25** [comment]
Good catch @XshreyasguptaX I think we need to add the criteria for RGSoC too would you be willing to make a PR?

**Comment by sakshivij** [comment]
According to my knowledge outreachy internship is open to all. The mentioned categories are correct but not necessary to participate in it. Mostly it is for beginners.

**Comment by sakshivij** [comment]
What do think @tapaswenipathak? Shouldn't the issue be closed in that case?
