### ISSUE TITLE
Add a timeline column

### ISSUE THREAD

**Issue by palash25** [tapaswenipathak/Open-Source-Internships#72]
It would be nice to have a timeline column to indicate from when to when the internship goes on so that students who want to apply for multiple SOC programs can get the information at one place and plan proposals accordingly

**Comment by rdrsadhu** [comment]
+1

**Comment by accakks** [comment]
This again is a subject to particular year. 
I can update this too for active project along with my comment on #83 , but won't this make table too big?

Or Should we add *** or something only for activity of current year and add this column?

**Comment by tapaswenipathak** [comment]
Timeline column would be nice.

**Comment by mridubhatnagar** [comment]
Is anyone currently working on this issue. I am interested in taking this up. Can submit the PR by tonight.

**Comment by accakks** [comment]
Hi @mridubhatnagar, I'll step aside, you can go ahead with this. Thanks!
