### ISSUE TITLE
Remove OWASP Code Sprint 

### ISSUE THREAD

**Issue by ujjawaljaiswal2017** [tapaswenipathak/Open-Source-Internships#75]
OWASP Code Sprint is not held anymore.

**Comment by palash25** [comment]
OWASP might organize it if it is not selected in GSoC. Some organizations do that.

It would be better if we just add a clause about it rather than removing it.

**Comment by ujjawaljaiswal2017** [comment]
Yes, that would be better.

**Comment by Abhishekguragol** [comment]
I would like to finish this issue could you please elaborate on what is to be done.
Thanks in advance.

**Comment by tapaswenipathak** [comment]
I will keep even if a SOC happened one time. When I participated I worked quiet a lot in finding the information. Let it be easily available.
