### ISSUE TITLE
Snowplow link leads to the Careers page

### ISSUE THREAD

**Issue by manaswinidas** [tapaswenipathak/Open-Source-Internships#78]
The Snowplow link leads to the Careers page but it should lead to [this link](https://snowplowanalytics.com/blog/2015/04/09/announcing-our-summer-internship-program/). That's a different thing that the latest internship announcement was on 2015.

**Comment by tapaswenipathak** [comment]
They announce the job posting on their blog. I read, let's only have careers section link.
