### ISSUE TITLE
Remove Radare SOC

### ISSUE THREAD

**Issue by Naveenaidu** [tapaswenipathak/Open-Source-Internships#83]
A recent mail conversation with the community member Pancake Nopcode of Radare, tells that Radare no longer has the resources nor the time to continue the program. They are now participating in GSOC.

In my opinion, `a field needs to be added in the list which tells which programs are active and which are not`. In this way people will still be able to know about the program and at the same time will also know about the `status` of the program.

There are few other programs in the list which have been deactivated.

**Comment by Naveenaidu** [comment]
A screen shot of the conversation.
![screenshot from 2018-08-26 22-15-33](https://user-images.githubusercontent.com/30195193/44630586-945e1500-a97d-11e8-9819-ad070d59c9f1.png)

**Comment by accakks** [comment]
@tapaswenipathak I think this is something needed to be verified each year. But as pointed by @Naveenaidu many of these programs are not active from a while/have been active only once or twice (example: Not getting selected in GSoC, some orgs launch their own SoC program for only that year).

Shall I go ahead and check activity? And make PR on the same?

**Comment by tapaswenipathak** [comment]
Even if a SoC happened one time ever, I will keep that in the list.
