### ISSUE TITLE
Add codefresh Fixvember

### ISSUE THREAD

**Issue by palash25** [tapaswenipathak/Open-Source-Internships#86]
Just like hacktoberfest but focussed at DevOps https://codefresh.io/fixvember/

**Comment by Sylfrena** [comment]
@palash25  @tapaswenipathak 
I made a [PR](https://github.com/tapaswenipathak/Open-Source-Internships/pull/91) regarding this. Please take a look and let me know if there's anything else I should add.

**Comment by emetowinner** [comment]
Fixvember link on  #91  returned error 404.......(page not found)

**Comment by emetowinner** [comment]
let me know if i can delete it from the list.
