### ISSUE TITLE
Add Kharagpur Winter of Code

### ISSUE THREAD

**Issue by mohitkh7** [tapaswenipathak/Open-Source-Internships#87]
[KWoC](https://kwoc.kossiitkgp.org/) is open source contribution competition organised by IIT Kharagur open source society in month of december.

**Comment by tapaswenipathak** [comment]
No college programmes. Feel free PRing https://github.com/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io. Please see http://opensourcehelpcommunity.herokuapp.com/contests/.
